# Generated by Django 5.0.7 on 2024-08-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saacademy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timestamp',
        ),
    ]
