# Generated by Django 5.0.7 on 2024-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saacademy', '0002_remove_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sub',
            field=models.CharField(max_length=10),
        ),
    ]
