# Generated by Django 5.0.7 on 2024-08-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saacademy', '0003_alter_contact_email_alter_contact_msg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='course/')),
                ('category', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
