# Generated by Django 5.0.7 on 2024-08-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saacademy', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='course/')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='sno',
            field=models.IntegerField(default=1),
        ),
    ]
